### PR TITLE
Fixed deprecated use of theNodeDefinition::setDeprecated method

### LINKED ISSUE #45: Deprecation thrown from DependencyInjection/Config when using symfony 5.1^ packages
Affected version:
`v1.1.1^`

Exception message:
`Since symfony/config 5.1: The signature of method "Symfony\Component\Config\Definition\Builder\NodeDefinition::setDeprecated()" requires 3 arguments: "string $package, string $version, string $message", not defining them is deprecated.`

### PR DESCRIPTION
**Pull request by KevinVanSonsbeek**
Fixes #45

### CODE REVIEW

File: src/DependencyInjection/Configuration.php [hunk 1]
```diff
@@ -50,4 +51,20 @@ public function getConfigTreeBuilder(): TreeBuilder
...
+        if (method_exists(BaseNode::class, 'getDeprecation')) {
+            return [
+                'nusje2000/feature-toggle-bundle',
+                $version,
+                $message,
+            ];
+        }
+
+        return [$message];
+    }
```
Comment (KevinVanSonsbeek) [inline src/DependencyInjection/Configuration.php:69]: This was done to keep bc with the 5.0 version of the symfony config component.

File: src/DependencyInjection/Configuration.php [hunk 2]
```diff
@@ -50,4 +51,20 @@ public function getConfigTreeBuilder(): TreeBuilder
 
         return $treeBuilder;
     }
+
+    /**
+     * @return array{0: string|null}|array{0: string, 1: string, 2:string|null}
+     */
+    private function getDeprecationParameters(string $version, ?string $message = null): array
```
Comment (nusje2000) [inline src/DependencyInjection/Configuration.php:58]: You never provide a message parameter, so I would prefer to leave this parameter out. Since the function is private, it can always be added later.

**Comment by nusje2000** [comment]
Thanks for creating this PR <3

File: src/DependencyInjection/Configuration.php (hunk 2 above)
Comment (KevinVanSonsbeek) [reply src/DependencyInjection/Configuration.php]: Removed the param

File: psalm.xml [hunk 3]
```diff
@@ -1,7 +1,6 @@
 <?xml version="1.0"?>
 <psalm
         errorLevel="1"
-        totallyTyped="true"
```
Comment (KevinVanSonsbeek) [inline psalm.xml:4]: Reason for the change: https://psalm.dev/docs/running_psalm/configuration/#totallytyped
